# Generated by Django 4.2.30 on 2026-06-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subsystem_type', models.CharField(choices=[('DF', 'Direction Finding'), ('MONITORING', 'Monitoring'), ('DRONE', 'Drone Detection'), ('SATELLITE', 'Satellite'), ('PASSIVE_CELLULAR', 'Passive Cellular'), ('ACTIVE_CELLULAR', 'Active Cellular'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=100)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], db_index=True, default='LOW', max_length=50)),
                ('event_type', models.CharField(choices=[('RF_THREAT', 'RF Threat'), ('DRONE_THREAT', 'Drone Threat'), ('COMMUNICATION_LOSS', 'Communication Loss'), ('SYNC_FAILURE', 'Synchronization Failure'), ('FREQUENCY_VIOLATION', 'Frequency Violation'), ('FORBIDDEN_SECTOR', 'Forbidden Sector Alert'), ('NODE_FAILURE', 'Node Failure'), ('CALIBRATION_FAILURE', 'Calibration Failure'), ('INFO', 'Informational')], default='INFO', max_length=100)),
                ('device_reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'event_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'created_at'], name='event_log_severit_b5bbbc_idx'), models.Index(fields=['subsystem_type', 'created_at'], name='event_log_subsyst_5ff32d_idx')],
            },
        ),
    ]
