# Generated by Django 4.2.30 on 2026-06-18 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('SESSION', 'Session'), ('SYSTEM', 'System'), ('EXPORT', 'Export'), ('ALERT', 'Alert')], default='SESSION', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=10)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('session_name', models.CharField(blank=True, default='', max_length=255)),
                ('action_type', models.CharField(blank=True, default='', max_length=100)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status', 'created_at'], name='notificatio_categor_e38252_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_22e6c2_idx'), models.Index(fields=['triggered_by', 'created_at'], name='notificatio_trigger_a9d998_idx')],
            },
        ),
    ]
