# Generated by Django 4.2.30 on 2026-06-18 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellularActiveTelemetry_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('node_id', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'cellular_active_telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CellularPassiveTelemetry_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('node_id', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'cellular_passive_telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DFTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_lat', models.FloatField(blank=True, null=True)),
                ('target_long', models.FloatField(blank=True, null=True)),
                ('target_frequency', models.FloatField(blank=True, null=True)),
                ('target_signal_bw', models.CharField(blank=True, max_length=50, null=True)),
                ('target_received_power', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'df_telemetry',
            },
        ),
        migrations.CreateModel(
            name='SatelliteTelemetry_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('node_id', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'satellite_telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_name', models.CharField(max_length=255)),
                ('operation_mode', models.CharField(blank=True, default='', max_length=50)),
                ('cyronics_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cognizant_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('monitoring_system_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('df_system_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('drone_detector_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cellular_active_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cellular_passive_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('satellite_interception_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, default='Manual', max_length=50)),
                ('node_id', models.CharField(blank=True, default='', max_length=100)),
                ('node_lat', models.FloatField(blank=True, null=True)),
                ('node_long', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('export_status', models.CharField(blank=True, db_index=True, default='PENDING', max_length=50)),
                ('polling_interval', models.IntegerField(default=10, help_text='Polling interval in seconds')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped')], db_index=True, default='CREATED', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telemetry_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='telemetry_s_status_2b289e_idx'), models.Index(fields=['session_id', 'status'], name='telemetry_s_session_44e3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('action_type', models.CharField(blank=True, default='', max_length=100)),
                ('module_name', models.CharField(blank=True, default='', max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='telemetry.telemetrysession', to_field='session_id')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_id', models.CharField(blank=True, default='', max_length=100)),
                ('subsystem_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('device_reference_id', models.CharField(blank=True, db_index=True, default='', help_text='node_id / drone_id / satellite_id / passive_cellular_id / active_cellular_id', max_length=100)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PENDING_RETRY', 'Pending Retry'), ('RETRYING', 'Retrying'), ('FAILED_MAX_RETRIES', 'Failed (Max Retries)'), ('SENT_ON_RETRY', 'Sent On Retry'), ('SUCCESS', 'Success')], db_index=True, default='PENDING', max_length=30)),
                ('retry_count', models.IntegerField(default=0)),
                ('polling_interval', models.IntegerField(default=10, help_text='Polling interval (seconds)')),
                ('last_sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_retry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_failure_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('exported_records', models.IntegerField(default=0)),
                ('csv_file_name', models.CharField(blank=True, default='', max_length=500)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('transfer_status', models.CharField(blank=True, default='', max_length=50)),
                ('sync_message', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_statuses', to='device.deviceinfo')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='telemetry.telemetrysession', to_field='session_id')),
            ],
            options={
                'db_table': 'sync_status',
                'ordering': ['-last_sync_timestamp'],
                'indexes': [models.Index(fields=['session', 'sync_status'], name='sync_status_session_53865b_idx'), models.Index(fields=['subsystem_type', 'device_reference_id'], name='sync_status_subsyst_9a17aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('node_id', models.CharField(db_index=True, max_length=100)),
                ('center_frequency_hz', models.BigIntegerField(blank=True, null=True)),
                ('threshold_dbm', models.FloatField(blank=True, null=True)),
                ('freq_mhz', models.FloatField(blank=True, null=True)),
                ('power_dbm', models.FloatField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, default='', max_length=100)),
                ('modulation', models.CharField(blank=True, default='', max_length=100)),
                ('bandwidth_3dbm_khz', models.FloatField(blank=True, null=True)),
                ('occupied_bandwidth_khz', models.FloatField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('sinad', models.FloatField(blank=True, null=True)),
                ('thd', models.FloatField(blank=True, null=True)),
                ('symbol_rate', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='device.deviceinfo')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='telemetry.telemetrysession', to_field='session_id')),
            ],
            options={
                'db_table': 'monitoring_telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='monitoring__session_be75c8_idx'), models.Index(fields=['node_id', 'timestamp'], name='monitoring__node_id_233717_idx')],
            },
        ),
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('drone_id', models.CharField(db_index=True, max_length=100)),
                ('drone_detected', models.BooleanField(default=False)),
                ('drone_type', models.CharField(blank=True, default='', max_length=100)),
                ('drone_latitude', models.FloatField(blank=True, null=True)),
                ('drone_longitude', models.FloatField(blank=True, null=True)),
                ('operator_latitude', models.FloatField(blank=True, null=True)),
                ('operator_longitude', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='device.deviceinfo')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='telemetry.telemetrysession', to_field='session_id')),
            ],
            options={
                'db_table': 'drone_telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='drone_telem_session_a9351c_idx'), models.Index(fields=['drone_id', 'timestamp'], name='drone_telem_drone_i_1074ce_idx')],
            },
        ),
    ]
