# Generated by Django 4.2.30 on 2026-06-18 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('device_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('DF', 'DF'), ('DRONE', 'Drone'), ('SATELLITE', 'Satellite'), ('MONITORING_SENSOR', 'Monitoring'), ('PASSIVE_CELL', 'Passive Cell'), ('ACTIVE_CELL', 'Active Cell')], default='DF', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, help_text='Device port', null=True)),
                ('node_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('node_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Device latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Device longitude', null=True)),
                ('operating_status', models.CharField(blank=True, choices=[('MASTER', 'Master'), ('REMOTE', 'Remote')], help_text='MASTER or REMOTE', max_length=20, null=True)),
                ('heartbeat_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=50, null=True)),
                ('network_status', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=50, null=True)),
                ('telemetry_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default=None, help_text='Device status e.g. active, inactive', max_length=50, null=True)),
                ('station_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csvrunning_status', models.IntegerField(default=0, help_text='0=offline, 1=CSV generation active', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('master_device', models.ForeignKey(blank=True, help_text='Master device this node belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nodes', to='device.deviceinfo')),
            ],
            options={
                'db_table': 'device_info',
                'ordering': ['-telemetry_timestamp'],
                'indexes': [models.Index(fields=['device_type', 'telemetry_timestamp'], name='device_info_device__3b3331_idx'), models.Index(fields=['network_status', 'telemetry_timestamp'], name='device_info_network_485eac_idx'), models.Index(fields=['heartbeat_status', 'telemetry_timestamp'], name='device_info_heartbe_931250_idx')],
            },
        ),
    ]
