# Generated by Django 4.2.30 on 2026-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='quard_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Mumbai'), (2, 'Pune')], help_text='1=Mumbai, 2=Pune', null=True),
        ),
    ]
