# Generated by Django 4.2.30 on 2026-06-19 06:54

from django.db import migrations, models
import django.db.models.deletion


def seed_quards(apps, schema_editor):
    Quard = apps.get_model("device", "Quard")
    for pk, name in [(1, "Mumbai"), (2, "Pune")]:
        Quard.objects.get_or_create(id=pk, defaults={"name": name})


def unseed_quards(apps, schema_editor):
    Quard = apps.get_model("device", "Quard")
    Quard.objects.filter(id__in=[1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_add_quard_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quard",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "quard",
                "verbose_name_plural": "quards",
                "db_table": "quard",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(seed_quards, unseed_quards),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="deviceinfo",
                    name="quard_id",
                ),
                migrations.AddField(
                    model_name="deviceinfo",
                    name="quard",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="quard_id",
                        help_text="Location quard (see Quard table to add more)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="device.quard",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        UPDATE device_info
                        SET quard_id = NULL
                        WHERE quard_id IS NOT NULL
                          AND quard_id NOT IN (SELECT id FROM quard);
                        ALTER TABLE device_info
                        ADD CONSTRAINT device_info_quard_id_fk
                        FOREIGN KEY (quard_id) REFERENCES quard(id)
                        ON DELETE SET NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE device_info
                        DROP CONSTRAINT IF EXISTS device_info_quard_id_fk;
                    """,
                ),
            ],
        ),
    ]
