import uuid
from django.core.management.base import BaseCommand
from django.utils import timezone
from device.models import DeviceInfo


class Command(BaseCommand):
    help = 'Add dummy data to device_info table'

    def handle(self, *args, **kwargs):
        
        dummy_devices = [
            # Mumbai HQ - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.1',
                'port': 8080,
                'node_id': 'DF-001',
                'node_name': 'antenna 1',
                'latitude': 19.0760,
                'longitude': 72.8777,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'mumbai',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.9',
                'port': 8088,
                'node_id': 'DF-003',
                'node_name': 'antenna 3',
                'latitude': 19.0755,
                'longitude': 72.8765,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'mumbai',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.2',
                'port': 8081,
                'node_id': 'DRONE-001',
                'node_name': 'Drone Alpha',
                'latitude': 19.0765,
                'longitude': 72.8780,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'mumbai',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.5',
                'port': 8084,
                'node_id': 'MON-001',
                'node_name': 'Monitoring Sensor A',
                'latitude': 19.0790,
                'longitude': 72.8800,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'mumbai',
                'csvrunning_status': 0,
            },
            # Pune Station - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.8',
                'port': 8087,
                'node_id': 'DF-002',
                'node_name': 'antenna 2',
                'latitude': 18.5220,
                'longitude': 73.8580,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Pune Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.12',
                'port': 8091,
                'node_id': 'DF-006',
                'node_name': 'antenna 6',
                'latitude': 18.5230,
                'longitude': 73.8590,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Pune Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.13',
                'port': 8092,
                'node_id': 'DRONE-004',
                'node_name': 'Drone Delta',
                'latitude': 18.5240,
                'longitude': 73.8600,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'Pune Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.14',
                'port': 8093,
                'node_id': 'MON-004',
                'node_name': 'Monitoring Sensor D',
                'latitude': 18.5250,
                'longitude': 73.8610,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Pune Station',
                'csvrunning_status': 1,
            },
            # Nagpur Station - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.15',
                'port': 8094,
                'node_id': 'DF-007',
                'node_name': 'antenna 7',
                'latitude': 21.1458,
                'longitude': 79.0882,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Nagpur Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.16',
                'port': 8095,
                'node_id': 'DF-008',
                'node_name': 'antenna 8',
                'latitude': 21.1468,
                'longitude': 79.0892,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'Nagpur Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.17',
                'port': 8096,
                'node_id': 'DRONE-005',
                'node_name': 'Drone Epsilon',
                'latitude': 21.1478,
                'longitude': 79.0902,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Nagpur Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.18',
                'port': 8097,
                'node_id': 'MON-005',
                'node_name': 'Monitoring Sensor E',
                'latitude': 21.1488,
                'longitude': 79.0912,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Nagpur Station',
                'csvrunning_status': 1,
            },
            # Delhi Station - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.10',
                'port': 8089,
                'node_id': 'DF-004',
                'node_name': 'antenna 4',
                'latitude': 28.6139,
                'longitude': 77.2090,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Delhi Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.19',
                'port': 8098,
                'node_id': 'DF-009',
                'node_name': 'antenna 9',
                'latitude': 28.6149,
                'longitude': 77.2100,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Delhi Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.3',
                'port': 8082,
                'node_id': 'DRONE-002',
                'node_name': 'Drone Beta',
                'latitude': 28.6150,
                'longitude': 77.2100,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'Delhi Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.20',
                'port': 8099,
                'node_id': 'MON-006',
                'node_name': 'Monitoring Sensor F',
                'latitude': 28.6160,
                'longitude': 77.2110,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Delhi Station',
                'csvrunning_status': 1,
            },
            # Bangalore Station - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.11',
                'port': 8090,
                'node_id': 'DF-005',
                'node_name': 'antenna 5',
                'latitude': 12.9716,
                'longitude': 77.5946,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Bangalore Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.21',
                'port': 8100,
                'node_id': 'DF-010',
                'node_name': 'antenna 10',
                'latitude': 12.9726,
                'longitude': 77.5956,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Bangalore Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.22',
                'port': 8101,
                'node_id': 'DRONE-006',
                'node_name': 'Drone Zeta',
                'latitude': 12.9736,
                'longitude': 77.5966,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Bangalore Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.6',
                'port': 8085,
                'node_id': 'MON-002',
                'node_name': 'Monitoring Sensor B',
                'latitude': 12.9720,
                'longitude': 77.5950,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Bangalore Station',
                'csvrunning_status': 1,
            },
            # Chennai Station - 2 DF, 1 Drone, 1 Monitoring
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.23',
                'port': 8102,
                'node_id': 'DF-011',
                'node_name': 'antenna 11',
                'latitude': 13.0827,
                'longitude': 80.2707,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Chennai Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DF,
                'ip_address': '192.168.0.24',
                'port': 8103,
                'node_id': 'DF-012',
                'node_name': 'antenna 12',
                'latitude': 13.0837,
                'longitude': 80.2717,
                'operating_status': DeviceInfo.OPERATING_MASTER,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Chennai Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_DRONE,
                'ip_address': '192.168.0.4',
                'port': 8083,
                'node_id': 'DRONE-003',
                'node_name': 'Drone Gamma',
                'latitude': 13.0847,
                'longitude': 80.2727,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_INACTIVE,
                'network_status': DeviceInfo.NETWORK_OFFLINE,
                'status': 'inactive',
                'station_name': 'Chennai Station',
                'csvrunning_status': 0,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '192.168.0.7',
                'port': 8086,
                'node_id': 'MON-003',
                'node_name': 'Monitoring Sensor C',
                'latitude': 13.0830,
                'longitude': 80.2710,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Chennai Station',
                'csvrunning_status': 1,
            },
            {
                'device_type': DeviceInfo.DEVICE_MONITORING,
                'ip_address': '10.10.202.31',
                'port': 8086,
                'node_id': 'MON-003',
                'node_name': '',
                'latitude': 28.6149,
                'longitude': 77.2080,
                'operating_status': DeviceInfo.OPERATING_REMOTE,
                'heartbeat_status': DeviceInfo.HEARTBEAT_ACTIVE,
                'network_status': DeviceInfo.NETWORK_ONLINE,
                'status': 'active',
                'station_name': 'Chennai Station',
                'csvrunning_status': 1,
            },
        ]

        created_count = 0
        updated_count = 0
        for device_data in dummy_devices:
            device_data.setdefault('quard_id', 1)
            device, created = DeviceInfo.objects.update_or_create(
                node_id=device_data['node_id'],
                defaults=device_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"Created device: {device.node_name}")
                )
            else:
                updated_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"Updated device: {device.node_name}")
                )

        self.stdout.write(
            self.style.SUCCESS(f"\nSuccessfully created {created_count} dummy devices, updated {updated_count} devices")
        )
